"""Schema building blocks that every table in this project shares.

Four things, and nothing else: how a row is identified, how a row is stamped
with time, what type a timestamp has, and what a country code looks like. They
are in one module because a table that quietly opted out of one of them would be
the kind of inconsistency nobody notices until a query returns the wrong answer
-- and because a rule written once cannot drift from a rule written twice.

Nothing here decides anything about the domain. These are the constraints that
apply regardless of what a row means.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import CheckConstraint, DateTime, String, Uuid, func
from sqlalchemy.orm import Mapped, declared_attr, mapped_column

#: The column type of a UUID primary key, and of every foreign key that points at
#: one. SQLAlchemy infers this from the `Mapped[uuid.UUID]` annotation of a
#: plain column, but a column declared with `ForeignKey(...)` carries no type to
#: infer from, and a foreign key whose type is not `UUID` to match its primary
#: key is a mismatch the database would only catch at runtime.
UuidId = Uuid(as_uuid=True)

#: Every timestamp in this schema is `timestamptz`, never a naive timestamp.
#:
#: A single alias rather than a repeated `DateTime(timezone=True)`, so "are we
#: storing an offset or not" is one decision instead of twenty. A naive
#: `created_at` cannot be compared against a provider-reported delivery date
#: from a different timezone, and the two are compared constantly.
UtcDateTime = DateTime(timezone=True)

#: The rule that a `country` column holds an upper-case ISO-3166 alpha-2 code.
#:
#: Upper case because a run's country is the scope for "N consecutive complete
#: runs": a lowercase `in` and an uppercase `IN` in two rows would silently
#: split one page's history in two, and neither half would look wrong.
#:
#: Exported as a constant, and attached through each table's `__table_args__`
#: rather than declared inside `mapped_column`, because **Alembic's autogenerate
#: does not detect check constraints declared on a column.** It emits the table
#: without them and then reports no drift, so the constraint exists in Python and
#: not in the database. Every check in this package therefore lives in
#: `__table_args__`, and `test_schema_integration` compares the live database's
#: checks against the metadata so the mistake cannot come back.
ISO_ALPHA_2_CHECK = "country ~ '^[A-Z]{2}$'"


class UuidPrimaryKeyMixin:
    """A UUID primary key, generated by the application.

    Client-side rather than `gen_random_uuid()` in the database, for one
    practical reason: an orchestrator inserting a parent and a child in a single
    flush needs the parent's id to build the child's foreign key, and a
    server-generated id is not knowable until the row is written. Ids are not
    sequential, so a row count cannot be inferred from a neighbouring id.
    """

    id: Mapped[uuid.UUID] = mapped_column(UuidId, primary_key=True, default=uuid.uuid4)


class TimestampMixin:
    """`created_at` and `updated_at`, both set by the database clock.

    The server clock rather than Python's, so rows written by the API, the
    worker and a migration all agree on what time it was.

    `updated_at` moves on ORM writes only. A bulk `UPDATE ... SET` issued as raw
    SQL would not bump it, because PostgreSQL has no `ON UPDATE CURRENT_TIMESTAMP`
    and expressing that properly needs a trigger on every table. No code path in
    this project issues a raw bulk update; a future one must say so.
    """

    created_at: Mapped[datetime] = mapped_column(
        UtcDateTime, server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        UtcDateTime, server_default=func.now(), onupdate=func.now(), nullable=False
    )


class CountryCodeMixin:
    """A mandatory ISO-3166 alpha-2 country code, two characters wide.

    Declared as a mixin rather than written out twice because the rule is only
    worth having if it is the *same* rule in both places. `facebook_pages.country`
    says where a page advertises; `collection_runs.country` scopes which
    country's run is being judged complete. A run whose country is not a real
    country code must be refused at the database, not discovered later as a run
    that never matches anything.

    The column is only half the rule -- each table must also add
    `CheckConstraint(ISO_ALPHA_2_CHECK, name="country_iso_alpha2")` to its
    `__table_args__`. The naming convention resolves that to
    `ck_<table>_country_iso_alpha2`, so the two are distinct constraints with the
    same name suffix.
    """

    @declared_attr
    def country(cls) -> Mapped[str]:  # noqa: N805
        return mapped_column(String(2), nullable=False)


def not_blank(column: str) -> CheckConstraint:
    """A named check rejecting a column that is present but empty.

    `NOT NULL` says a value must exist. It says nothing about whether the value
    is `''` or `'   '`, and an empty provider name is not a provider name. The
    column name is a literal at every call site in this package and never a value
    that arrived from outside, so interpolating it into the constraint text
    cannot carry an injection.
    """
    return CheckConstraint(f"btrim({column}) <> ''", name=f"{column}_not_blank")


def at_most(column: str, limit: int) -> CheckConstraint:
    """A named check bounding the length of a free-text column.

    `Text` is unbounded, and the column most likely to receive an entire HTML
    error page from a provider is the one an operator reads to find out why a run
    failed. Truncating is the caller's job; refusing to store a megabyte of
    provider HTML in an error field is the database's.
    """
    return CheckConstraint(f"length({column}) <= {limit}", name=f"{column}_max_length")
