"""The collection domain: tracking, runs, and raw responses.

Revision ID: 0002_collection_domain
Revises: 0001_pg_trgm
Create Date: 2026-09-30

Five tables, generated by `alembic revision --autogenerate` against the models
in `app.models` and then reviewed line by line. The chain is single-parented end
to end, and every foreign key is `ON DELETE RESTRICT`:

    competitors -> facebook_pages -> collection_runs -> provider_runs -> raw_responses

`RESTICT` rather than `CASCADE` is the point of the whole file. Commercial ads
that stop running disappear from Meta permanently, so this collected data
cannot be re-acquired; a cascade would let a deleted competitor silently take a
page's entire run history and every raw payload with it. Deleting collected data
has to be something someone writes on purpose, and the database refuses to
guess.

## What is deliberately absent

* **`users`, `settings`, `audit_logs`.** `ARCHITECTURE.md` lists them under
  slice-1 "Identity", but they exist to serve authentication, which AGENTS.md
  places after S3, and a `users` table here would mean choosing a password-hash
  column before the hashing design exists. Collection orchestration reads and
  writes none of them.
* **`ads`, `ad_snapshots` and every other ad table.** Those are S2. Creating
  them here would put the append-only history rules in the wrong checkpoint.
* **`jobs`.** S0.3's `PostgresJobQueue` names S1.2 as the checkpoint that
  supplies the table, and a queue table with no producer and no consumer is a
  table that can only be wrong.
* **A trigram or `tsvector` index.** `0001_pg_trgm` installed the extension
  precisely so the first GIN index can be built later, and the only text
  `ARCHITECTURE.md` asks to search is ad copy -- which is S2.1. The extension
  is verified still installed by `test_schema_integration`.

## The one hand-written object: `payload_hash_trigger`

A `BEFORE INSERT OR UPDATE` trigger that owns `raw_responses.payload_hash`.

The obvious implementation is a generated column,
`GENERATED ALWAYS AS (encode(sha256(convert_to(payload::text, 'UTF8')), 'hex')) STORED`.
It does not work, and it fails at `CREATE TABLE` with "generation expression is
not immutable": PostgreSQL requires a generated expression to be immutable and
the JSONB-to-text cast is not. A trigger has no such requirement.

The trigger buys a stronger property than an application-computed hash could.
The hash is a function of the stored payload, so it cannot be omitted, cannot be
supplied wrong, cannot be forged, and moves if the payload is ever edited. The
column is `NOT NULL` and the writer supplies nothing, which
`test_schema_integration` proves against the running database.

The hash covers the *stored* form, not the wire bytes. `jsonb` normalises key
order, whitespace and duplicate keys, so it identifies what we kept rather than
claiming byte-for-byte fidelity to the provider.

Reversibility: `downgrade()` drops the trigger before the function and both
before any table, so the function is never dropped while something references
it. **This downgrade has never been executed** -- it issues DROPs, and the
checkpoint rules forbid a destructive command without explicit human approval.
It is asserted structurally, and its SQL is rendered offline in
`test_schema_integration`.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_collection_domain"
down_revision: str | None = "0001_pg_trgm"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Schema-qualified so the function cannot collide with, or be resolved out of,
#: another schema's search_path in a database that has been customised.
_TRIGGER_FUNCTION = "public.raw_response_payload_hash"

#: The expression both the trigger and the tests recompute. Written once here so
#: the definition of "the fingerprint of a stored payload" has a single owner.
_HASH_EXPRESSION = "encode(sha256(convert_to(NEW.payload::text, 'UTF8')), 'hex')"


def upgrade() -> None:
    """Create the five tables, their indexes, and the payload-hash trigger."""
    op.create_table(
        "competitors",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(name) <> ''", name=op.f("ck_competitors_name_not_blank")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitors")),
    )
    op.create_table(
        "facebook_pages",
        sa.Column("competitor_id", sa.Uuid(), nullable=False),
        sa.Column("page_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("tracking_frequency", sa.String(length=64), nullable=False),
        sa.Column("is_tracked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.CheckConstraint(
            "btrim(page_id) <> ''", name=op.f("ck_facebook_pages_page_id_not_blank")
        ),
        sa.CheckConstraint(
            "btrim(tracking_frequency) <> ''",
            name=op.f("ck_facebook_pages_tracking_frequency_not_blank"),
        ),
        sa.CheckConstraint(
            "country ~ '^[A-Z]{2}$'", name=op.f("ck_facebook_pages_country_iso_alpha2")
        ),
        sa.CheckConstraint(
            "url IS NULL OR url ~ '^https?://'", name=op.f("ck_facebook_pages_url_http_only")
        ),
        sa.ForeignKeyConstraint(
            ["competitor_id"],
            ["competitors.id"],
            name=op.f("fk_facebook_pages_competitor_id_competitors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_facebook_pages")),
        sa.UniqueConstraint("page_id", name=op.f("uq_facebook_pages_page_id")),
    )
    op.create_index(
        "ix_facebook_pages_competitor_id", "facebook_pages", ["competitor_id"], unique=False
    )
    op.create_table(
        "collection_runs",
        sa.Column("facebook_page_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=255), nullable=False),
        sa.Column(
            "data_origin",
            sa.Enum(
                "official_api",
                "public_ui",
                "third_party",
                "user_import",
                name="data_origin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "complete",
                "partial",
                "failed",
                name="status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_returned", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_type", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.CheckConstraint(
            "btrim(provider) <> ''", name=op.f("ck_collection_runs_provider_not_blank")
        ),
        sa.CheckConstraint(
            "country ~ '^[A-Z]{2}$'", name=op.f("ck_collection_runs_country_iso_alpha2")
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at",
            name=op.f("ck_collection_runs_finished_after_started"),
        ),
        sa.CheckConstraint(
            "length(error_message) <= 2000",
            name=op.f("ck_collection_runs_error_message_max_length"),
        ),
        sa.CheckConstraint(
            "records_returned >= 0", name=op.f("ck_collection_runs_records_returned_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["facebook_page_id"],
            ["facebook_pages.id"],
            name=op.f("fk_collection_runs_facebook_page_id_facebook_pages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection_runs")),
    )
    op.create_index(
        "ix_collection_runs_facebook_page_id", "collection_runs", ["facebook_page_id"], unique=False
    )
    op.create_table(
        "provider_runs",
        sa.Column("collection_run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "succeeded",
                "failed",
                "blocked",
                name="status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("request_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("next_cursor", sa.Text(), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("error_type", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("cost_amount", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("cost_currency", sa.String(length=3), nullable=True),
        sa.Column("cost_method", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            # Split across two literals purely for line length; adjacent string
            # literals concatenate, so the emitted SQL is one statement. This is
            # the same text as the model, deliberately written out rather than
            # imported: a migration is a frozen record of what happened, and
            # importing it from `app.models` would let a later edit rewrite
            # history.
            "(cost_amount IS NULL AND cost_currency IS NULL AND cost_method IS NULL) OR "
            "(cost_amount IS NOT NULL AND cost_currency IS NOT NULL AND cost_method IS NOT NULL)",
            name=op.f("ck_provider_runs_cost_all_or_nothing"),
        ),
        sa.CheckConstraint(
            "cost_amount IS NULL OR cost_amount >= 0",
            name=op.f("ck_provider_runs_cost_amount_not_negative"),
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR finished_at >= started_at",
            name=op.f("ck_provider_runs_finished_after_started"),
        ),
        sa.CheckConstraint(
            "http_status IS NULL OR http_status BETWEEN 100 AND 599",
            name=op.f("ck_provider_runs_http_status_range"),
        ),
        sa.CheckConstraint(
            "length(error_message) <= 2000", name=op.f("ck_provider_runs_error_message_max_length")
        ),
        sa.ForeignKeyConstraint(
            ["collection_run_id"],
            ["collection_runs.id"],
            name=op.f("fk_provider_runs_collection_run_id_collection_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_runs")),
    )
    op.create_index(
        "ix_provider_runs_collection_run_id", "provider_runs", ["collection_run_id"], unique=False
    )
    op.create_table(
        "raw_responses",
        sa.Column("provider_run_id", sa.Uuid(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provider_run_id"],
            ["provider_runs.id"],
            name=op.f("fk_raw_responses_provider_run_id_provider_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_responses")),
        sa.UniqueConstraint("provider_run_id", name=op.f("uq_raw_responses_provider_run_id")),
    )

    # The trigger is invisible to autogenerate -- it is not a table, a column or
    # an index -- so it is written by hand here and removed by hand in the
    # downgrade. `_HASH_EXPRESSION` interpolates nothing at all: it is a literal
    # SQL expression, so there is no identifier and no value to escape.
    op.execute(
        f"""
        CREATE FUNCTION {_TRIGGER_FUNCTION}() RETURNS trigger
        LANGUAGE plpgsql AS $fn$
        BEGIN
            NEW.payload_hash := {_HASH_EXPRESSION};
            RETURN NEW;
        END;
        $fn$
        """
    )
    op.execute(
        """
        CREATE TRIGGER raw_responses_payload_hash_trg
        BEFORE INSERT OR UPDATE ON raw_responses
        FOR EACH ROW EXECUTE FUNCTION raw_response_payload_hash()
        """
    )


def downgrade() -> None:
    """Remove the trigger, its function, and the five tables.

    **Never executed.** It issues DROPs, and running a destructive database
    command needs explicit human approval. `test_schema_integration` renders this
    function's SQL offline instead of running it, and asserts the order.
    """
    # Trigger before function: dropping the function first would leave a trigger
    # pointing at nothing, and the table drop would fail on the dependency.
    op.execute("DROP TRIGGER IF EXISTS raw_responses_payload_hash_trg ON raw_responses")
    op.execute(f"DROP FUNCTION IF EXISTS {_TRIGGER_FUNCTION}()")
    op.drop_table("raw_responses")
    op.drop_index("ix_provider_runs_collection_run_id", table_name="provider_runs")
    op.drop_table("provider_runs")
    op.drop_index("ix_collection_runs_facebook_page_id", table_name="collection_runs")
    op.drop_table("collection_runs")
    op.drop_index("ix_facebook_pages_competitor_id", table_name="facebook_pages")
    op.drop_table("facebook_pages")
    op.drop_table("competitors")
